kite-sdk/kite

src/site/site.xml
The blank-maven-skin is already published and works when the content is
embedded in the jekyll site as well.
=> CDK-870: Use blank skin instead of custom empty skin.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/DatasetRecordException.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/DatasetWriter.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/AvroAppender.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemWriter.java
This is similar to Avro's AppendWriteException and signals that a write
operation failed because an invalid (or otherwise unusable) record was
passed in, but the writer can still be used.
=> CDK-864: Add DatasetRecordException.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVFileReader.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVRecordBuilder.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVRecordParser.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVUtil.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemProperties.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestCSVFileReader.java
Extracts the Avro record building from CSVFileReader into CSVRecordBuilder
that can be used by passing an already-parsed String[]. Adds
CSVRecordParser that wraps a CSVParser, which will parse a single line
of CSV passed as a String. This is to support changes to the flume sink
that can read events with CSV payloads.
=> CDK-845: Refactor CSV to support String parsing.

kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveSchemaConverter.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveUtils.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestManagedExternalHandling.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestSchemaConversion.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestTableConversion.java, pom.xml
Tables created in Hive using STORED AS AVRO do not have a schema URI or
literal in the table properties. Instead, the schema is generated from
the table DDL when writing. This translates from table DDL if no schema
is set. This also fixes tables created with STORED AS PARQUET.
=> CDK-677: Add translation from Hive DDL to Schema.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/DatasetWriter.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/Flushable.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/Syncable.java
This deprecates the DatasetWriter#flush and #sync methods, which are
replaced by Flushable#flush. Sync needed to call flush to guarantee the
records were durable, but flush was still exposed, requiring callers to
flush and sync, with sync calling flush immediately afterwards. Instead,
the new Flushable interface carries a stronger guarantee that records
have not only been flushed to the underlying buffer, but that they are
persisted to disk also.
=> CDK-863: Deprecate DatasetWriter flush/sync, add Flushable.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/DatasetException.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/DatasetOperationException.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemWriter.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/PartitionedDatasetWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestAvroWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemWriters.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestParquetWriter.java
This updates the FileSystemWriter's error handling. First,
RuntimeException is now caught throughout the class to ensure that
unknown exceptions in appenders (or FS calls) cannot put the writer in
an unknown state. Second, this updates the close method so that it
handles more error cases correctly:
* After a call to close, the writer state is always CLOSED
* Close does nothing when writer is NEW or CLOSED
* Close is called (on Appender) only if the writer is not in ERROR
* A data file is released if:
1. Data has been written to the file
2. Data has been committed with a flush() or sync()
3. The writer is not in an ERROR state
* If a data file is not to be released, it is discarded
* Appender cleanup is called for OPEN or ERROR
* Any failure in close will prevent the next close task
* No …
=> CDK-885: Fix FS writer error handling.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/PartitionListener.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemView.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestPartitionedDatasetWriter.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveAbstractMetadataProvider.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/MetaStoreUtil.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveExternalDatasetRepository.java
The partition listener now listens to partition removal events and updates the Hive metastore appropriately.
=> CDK-924: update the Hive metastore when partitions are removed.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemViewKeyInputFormat.java, kite-data/kite-data-crunch/pom.xml, kite-data/kite-data-crunch/src/test/avro/newuser.avsc, kite-data/kite-data-crunch/src/test/java/org/kitesdk/data/crunch/TestCrunchDatasets.java
If a Dataset is loaded with a specific Avro type provided by the caller, that type is effectively the reader schema and should be honored by MapReduce jobs. This PR simply sets the reader schema appropriately in the input format and includes a test to ensure it is used.
=> CDK-927: Use requested type as reader schema in MapReduce jobs.

kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/SchemaCommand.java
The error is that datasets may be null and is always (not conditionally)
dereferenced. This is actually checked by a precondition so the code is
safe.
=> CDK-937: Fix findbugs error.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemMetadataProvider.java
The problem was that the FileSystem implementation was returning
multiple "default" namespaces. The implementation now uses a Set to
accumulate both namespaces and dataset names.
The bug only happened when a repository namespace path was used instead
of a repository. In that case, the single namespace appears to be a
valid repository with tables in the default namespace. Each table in the
default namespace would result in another "default" in the list of
namespaces. When Datasets.list listed the tables in each namespace, all
of the tables were present in each copy of default, which resulted in
n^2 results.
=> CDK-955: Fix duplicate URIs from Datasets.list.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/URIPattern.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/TestURIPattern.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestHDFSDatasetURIs.java
This updates the URIPattern code to ignore trailing slashes in URIs.
URIs can still match a trailing / explicitly, and URI pattern globbing
still works as before.
=> CDK-945: Ignore trailing slash in URIs.

kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemView.java
Super trivial change to correct an assertion message that was copy/pasted incorrectly.
=> Corrected incorrect assertion message.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/IncompatibleSchemaException.java, kite-tools-parent/kite-tools/src/test/java/org/kitesdk/cli/commands/TestSchemaCommandMerge.java
Now throws IncompatibleSchemaException instead of ValidationException.
=> CDK-970: Fix IncompatibleSchemaException.check.

kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveUtils.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveUtils.java
Kite sets the table DDL when it creates a table and should update the
DDL if the schema changes.
Contributed by Andrew Stevenson.
=> CDK-974: Update Hive DDL when updating a table.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/PartitionedDatasetWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestDatasetWriterCacheLoader.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveExternalMetadataProvider.java
* Added a test of `load()` methods of `DatasetWriterCacheLoader` and
`IncrementalDatasetWriterCacheLoader`.
* Moved the `writer.initialize()` call to happen before the
`listener.partitionAdded()` call in `DatasetWriterCacheLoader#load`
and `IncrementalDatasetWriterCacheLoader#load`.
=> CDK-615: Permissions issue writing to a partitioned Hive external dataset

kite-morphlines/kite-morphlines-metrics-servlets/src/test/java/org/kitesdk/morphline/metrics/servlets/HttpMetricsMorphlineTest.java
The documentation of URLConnection.getInputStream() is that it may throw IOException. Which derived IOException which are thrown though is somewhat platform dependent. For some of the platforms a closed socket will instead throw SocketException.
=> CDK-989: HttpMetricsMorphlineTest assumes only ConnectionException 

kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/Main.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/tools/TransformTask.java, kite-tools-parent/kite-tools/src/main/resources/kite-cli-logging.properties, kite-tools-parent/kite-tools/src/test/java/org/kitesdk/cli/commands/TestCSVImportCommand.java
This is based on #303, but fixes the logging configuration so that a link to the MR job is given when running on a cluster and task errors are printed to the console when running locally.
=> CDK-898: Use MRPipeline instead of MemPipeline

kite-morphlines/kite-morphlines-hadoop-rcfile/src/main/java/org/kitesdk/morphline/hadoop/rcfile/ReadRCFileBuilder.java, kite-morphlines/kite-morphlines-hadoop-rcfile/src/test/java/org/kitesdk/morphline/hadoop/rcfile/ReadRCFileTest.java
Test case failed with the same error without the fix and passes with the fix.
=> CDH-27606 Fix Morphlines.ReadRCFile to read null values in RCFile

.gitignore, kite-data/kite-data-core/src/main/java/org/kitesdk/data/Signalable.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/Constraints.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/SignalManager.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/predicates/In.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/predicates/Predicates.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/predicates/RegisteredPredicate.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/TestRefinableViews.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestDatasetWriterCacheLoader.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemDataset.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemView.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestPartitionedDatasetWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestSignalManager.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/predicates/TestInToFromString.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/predicates/TestRegisteredPredicateToFromString.java, kite-data/kite-data-crunch/src/main/java/org/kitesdk/data/crunch/DatasetTarget.java, kite-data/kite-data-crunch/src/test/java/org/kitesdk/data/crunch/TestCrunchDatasets.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java, kite-data/kite-data-mapreduce/src/test/java/org/kitesdk/data/mapreduce/TestMapReduce.java
Implementation for hdfs and hive based views, hbase is currently unimplemented.
Includes updates to interfaces for views for the basic signalReady/isReady concept
Updates were also made to the dataset repository interface to create these signals for datasets based on constraints, and to determine the last time those constraints were signaled.
MapReduce was updated to create these signals (if possible) when a write to a dataset is successful. Crunch was updated to support using these signals for WriteMode.CHECKPOINT (with a 'ready' view essentially indicating a previous success)
=> CDK-451 signal ready views

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/Replaceable.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemPartitionView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemUtil.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemView.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestPartitionReplacement.java, kite-data/kite-data-crunch/src/main/java/org/kitesdk/data/crunch/DatasetTarget.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java, kite-data/kite-data-mapreduce/src/test/java/org/kitesdk/data/mapreduce/TestMapReduce.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/Main.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/BaseDatasetCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/CompactCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/CopyCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/DeleteCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/tools/CompactionTask.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/tools/TransformTask.java
This is a work-in-progress. This adds a replace method, similar to merge, that replaces a partition. The use case is to copy data out of a dataset with MR and then replace the original partitions with the rewritten partition, which compacts the data.
The first commit adds `PartitionView` as discussed on the mailing list, and adds `getCoveringPartitions` to the `View` API. The second commit rewrites merge and adds replace in terms of those partition views.
=> CDK-843: Add replace to rewrite partitions

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/CharSequences.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/predicates/In.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/predicates/Predicates.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/TestViewUris.java
Tracked down more hash sets in use and replaced with linked hash sets.
=> CDK-983: Fix in predicate ordering.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/DefaultConfiguration.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyInputFormat.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java, kite-data/kite-data-mapreduce/src/test/java/org/kitesdk/data/mapreduce/FileSystemTestBase.java
This sets the default configuration using the one passed to the InputFormat or OutputFormat when running in a MR task. To avoid this setting leaking into tests, this adds `DefaultConfiguration.init(Configuration)`, which will set the default conf only if it has not already been set via `set` or `init`. (Otherwise, test fail.)
This replaces #368.
=> CDK-976: Fix task configuration in MR

kite-data/kite-data-core/src/main/java/org/kitesdk/data/View.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/AbstractDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/AbstractRefinableView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/DataModelUtil.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/EntityAccessor.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVFileReader.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVInputFormat.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemViewKeyInputFormat.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/JSONFileReader.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/JSONInputFormat.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/MultiFileDatasetReader.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemDatasetRepository.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestProjection.java, kite-data/kite-data-hbase/src/main/java/org/kitesdk/data/hbase/DaoView.java, kite-data/kite-data-hbase/src/main/java/org/kitesdk/data/hbase/avro/AvroEntityComposer.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyInputFormat.java, kite-data/kite-data-mapreduce/src/test/java/org/kitesdk/data/mapreduce/TestDatasetRecordWriter.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/BaseDatasetCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/CopyCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/CreateDatasetCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/UpdateDatasetCommand.java, kite-tools-parent/kite-tools/src/test/java/org/kitesdk/cli/commands/TestCopyCommandCluster.java, kite-tools-parent/kite-tools/src/test/java/org/kitesdk/cli/commands/TestCopyCommandClusterChangedNameWithPartitioning.java, kite-tools-parent/kite-tools/src/test/java/org/kitesdk/cli/commands/TestCopyCommandClusterNewField.java, kite-tools-parent/kite-tools/src/test/java/org/kitesdk/cli/commands/TestCopyCommandClusterSchemaEvolution.java
This extends Joey's PR, #346, and fixes the review issues I noted. One of the main issues was that without changing the backing dataset's type class, projection would fail. This adds `asType` projection to take care of that issue.
=> CDK-973: Add View#asSchema and View#asType projection methods

kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java
This happens only when a dataset instance is passed to the configuration
methods. The fix is to verify that the target dataset is not the root by
inspecting whether the partition key has any values.
=> CDK-1016: Fix OutputFormat writing directly to datasets.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/Replaceable.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestPartitionReplacement.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java
This removes any partitions in the view being replaced, even if the
replacement doesn't have the partition.
=> CDK-1017: Remove all target partitions in replace.

kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java, kite-data/kite-data-mapreduce/src/test/java/org/kitesdk/data/mapreduce/TestDatasetRecordWriter.java, pom.xml
It appears that this was working around PARQUET-62, which fixed
dictionary support when incoming records are reused. Updating to 1.6.0
brings in the Parquet fix.
This also adds a property, kite.copyOutputRecords, that allows users to
control whether records should be copied. This defaults to false, but is
a good safety valve in case of other bugs like PARQUET-62.
=> CDK-1018: Avoid unnecessary copy in MR output format.

kite-tools-parent/kite-tools/src/main/java/org/kitesdk/cli/commands/CopyCommand.java, kite-tools-parent/kite-tools/src/main/java/org/kitesdk/tools/TransformTask.java
This takes the delegation token code from the CopyCommand and moves it
into TransformTask so that all of the transform-based commands will work
with Hive.
=> CDK-1019: Move Hive token setup into TransformTask.

kite-morphlines/kite-morphlines-hadoop-sequencefile/src/main/java/org/kitesdk/morphline/hadoop/sequencefile/ReadSequenceFileBuilder.java
The morphline command ReadSequenceFile was only reading the first record from the sequence file because the reader assumes some length of the root directory. This prematurely closes the reader before it scans for subsequent records.
=> CDK-1012: Properly use the SequenceFile.reader.stream to pass in record stream

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemWriter.java
Keeping the number of records written in an int caused a bug where
writing more than Integer.MAX_VALUE records (~2B) would overflow the
counter and the check to see whether any records had been written would
fail because count is less than 0. The fix is to use a long.
=> KITE-1053: Fix int overflow bug in FS writer.

kite-hbase-dependencies/cdh5-test/pom.xml, kite-hbase-dependencies/cdh5/pom.xml, kite-tools-parent/kite-tools-cdh5/pom.xml
The CDH5 HBase dependency bundle was transitively pulling in the MR1
version of hadoop-core. That was conflicting with Yarn MR classes and
causing a runtime VerifyError.
This also updates to use the right CDH5 crunch version.
=> KITE-1024: Fix kite-tools tarball dependencies.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/ClockReady.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/DescriptorUtil.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/RollingWriter.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/AvroAppender.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/CSVAppender.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/DurableParquetAppender.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemProperties.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemWriter.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/ParquetAppender.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/PartitionedDatasetWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestAvroWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestDatasetWriterCacheLoader.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemWriters.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestParquetWriter.java
File size-based rolling works and is passing a new test for Avro, but is
disabled for Parquet because the appender has no reliable size estimate
for Parquet.
Time-based rolling uses a new SPI interface, ClockReady, which exposes a
method for passing time signals to implementing classes. This removes
the need for Kite to provide a thread-based check.
=> CDK-991: Add size-based and time-based file rolling.

kite-data/kite-data-crunch/src/test/java/org/kitesdk/data/crunch/TestCrunchDatasetsHive.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveAbstractMetadataProvider.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/MetaStoreUtil.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestExternalBackwardCompatibility.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveDatasetURIs.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveDatasetURIsCompatibility.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveDatasetURIsWithDefaultConfiguration.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveExternalDatasetRepository.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveExternalMetadataProvider.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveManagedDatasetRepository.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveManagedMetadataProvider.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHivePartitioning.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestHiveRepositoryURIs.java, kite-data/kite-data-hive/src/test/java/org/kitesdk/data/spi/hive/TestManagedExternalHandling.java
This adds a MetaStoreUtil.get method that keeps track of util objects
(and the internal MetaStore connection) by connection URIs. These are
safe to share because they are thread-safe.
=> KITE-1040: Cache Hive MetaStore connections.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/DefaultConfiguration.java
Oozie passes delegation tokens via HADOOP_TOKEN_FILE_LOCATION. This adds
support to pick up those tokens and add them to the DefaultConfiguration.
=> KITE-1065: Add support for Oozie delegation tokens.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/DatasetDescriptor.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/PartitionView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDatasetRepository.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemPartitionView.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemUtil.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemDataset.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemPartitionView.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemUtil.java, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveExternalMetadataProvider.java
This adds test for URIs with escaped characters and fixes handling in
the FS PartitionView implementation. The implementation was accidentally
unescaping URIs by using URI.create, which expects escaped characters,
along with URI#getPath, which will remove escapes.
This also fixes the URI returned by getLocation. This previously used
Path#getUri, but that method returns the Path's internal URI that
is double-escaped. Returning a URI created from Path#toString is the
correct behavior because it matches the Path passed in. Similarly,
the merge and replace methods in the FS dataset implementation that rely
on Paths created from those locations have been updated to correctly
construct a Path from a URI by converting the URI to a String rather
than setting the internal URI directly.
=> KITE-1023: Fix PartitionView URI escaping.

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemDataset.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/SignalManager.java
The CLI will create a dataset around a single data file, but the
FileSystemDataset code assumed that the path it uses is a directory.
This caused errors because the signal manager attempted to use the
incoming data file path as a directory that potentially contained the
signals folder. This updates the FileSystemDataset to use the data
file's parent for the signal path.
=> KITE-1057: Fix signal path for single data file.

kite-tools-parent/kite-tools/src/main/java/org/kitesdk/tools/TransformTask.java
This removes the work-around added for KITE-898, where job submission
was failing when importing local-to-HDFS unless the default FS was
local. This is no longer needed and is causing a different failure.
=> KITE-1073: Remove work-around setting default FS in CLI.

kite-data/kite-data-crunch/pom.xml
The test fails in job setup using the local job runner when the HBase
test has been run first. It appears to be a bug in the test runner code
that can be avoided by not reusing test VMs for the Crunch module.
=> KITE-1076: Fix flaky Crunch-Hive test.

kite-tools-parent/kite-tools/src/main/java/org/kitesdk/tools/TransformTask.java, kite-tools-parent/pom.xml, pom.xml
This changes the way jobs submitted by the CLI are configured.
Previously, the entire lib directory for Hive was added to the
distributed cache. This caused long job and task startup times and
exposed some conflicting jar problems. This commit updates the setup so
that individual jars are added for classes needed for interacting with
the Hive MetaStore. In cases where the job is local or the job isn't
interacting with Hive, this doesn't add Hive dependencies to the
distributed cache at all.
=> KITE-1083: Add single jars to DistCache for Hive.

kite-data/kite-data-oozie/src/main/java/org/kitesdk/data/oozie/KiteConfigurationService.java, kite-data/kite-data-oozie/src/main/java/org/kitesdk/data/oozie/KiteURIHandler.java, kite-data/kite-data-oozie/src/test/java/org/kitesdk/data/oozie/MiniDFSTest.java, kite-data/kite-data-oozie/src/test/java/org/kitesdk/data/oozie/TestKiteConfigurationService.java, kite-data/kite-data-oozie/src/test/java/org/kitesdk/data/oozie/TestKiteURIHandler.java
https://issues.cloudera.org/browse/KITE-1035
Alternative implementation of the concept introduced first in pull #399
Sets the default configuration for kite to a list of configuration sources set at the property "oozie.service.KiteConfigurationService.kite.configuration"
(A consumer would also need to add the configuration service to the list of configurations specified for oozie under "oozie.services")
=> KITE-1035 added kite configuration service for oozie to supplement the KiteURIHandler

kite-data/kite-data-s3/src/main/java/org/kitesdk/data/spi/s3/Loader.java
Minor change to fix https://issues.cloudera.org/browse/KITE-1102
=> KITE-1102: Correct URI pattern registrations for s3a protocol

kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemProperties.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemUtil.java, kite-data/kite-data-core/src/main/java/org/kitesdk/data/spi/filesystem/FileSystemWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestAvroObjectStoreWriter.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestAvroWriterWithoutRename.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemUtil.java, kite-data/kite-data-core/src/test/java/org/kitesdk/data/spi/filesystem/TestFileSystemWriters.java, kite-data/kite-data-mapreduce/src/main/java/org/kitesdk/data/mapreduce/DatasetKeyOutputFormat.java
Pull request for https://issues.cloudera.org/browse/KITE-1118
For importing about 20 GB of data into S3, this provided approximately an 8x job speedup, from 40 min to 5 min.
=> KITE-1118: Optimize writing data to S3

kite-morphlines/kite-morphlines-core/src/main/java/org/kitesdk/morphline/stdlib/HashDigestBuilder.java, kite-morphlines/kite-morphlines-core/src/test/java/org/kitesdk/morphline/stdlib/HashDigestTest.java, kite-morphlines/kite-morphlines-core/src/test/resources/test-morphlines/hashDigest.conf, kite-morphlines/src/site/confluence/morphlinesReferenceGuide.confluence
Initial commit for hashCommand implementation and tests
=> Morphlines hashDigest command

kite-morphlines/kite-morphlines-solr-core/pom.xml, pom.xml
Corresponding JIRA is here: https://issues.cloudera.org/browse/KITE-1126
=> KITE-1126: Update morphlines to use Solr6.3.0 instead of Solr4

README.md, kite-data/kite-data-hive/src/main/java/org/kitesdk/data/spi/hive/HiveUtils.java, pom.xml
* according to the readme default should be java 7 so might as well update the target version property
* In top level pom.xml the maven compiler plugin to use the javaVersion property instead of the hard coded 1.6 value
* Some warnings had to be fixed in HiveUtils, because of the -Werror (error on warnings) maven flag
=> KITE-1137 update javaVersion to 1.7 and fix warnings
